---
title: "Example"
author:
- name: Xiaotao Shen (https://www.shenxt.info/)
- affiliation: School of Medicine, Stanford University
  url: http://shenxt.info/
date: "Created on 2021-12-04 and updated on `r Sys.Date()`"
output:
  html_document:
    df_print: paged
    toc: no
  pdf_document:
    toc: no
vignette: >
  %\VignetteIndexEntry{example}
  %\VignettePackage{massdataset}
  % \VignetteEngine{knitr::rmarkdown}
  % \usepackage[utf8]{inputenc}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE, echo=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = TRUE,
  out.width = "100%"
)
```


# **Example 1**

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=FALSE}
library(massdataset)
library(tidyverse)

data("expression_data")
data("sample_info")
data("sample_info_note")
data("variable_info")
data("variable_info_note")

object =
  create_mass_dataset(
    expression_data = expression_data,
    sample_info = sample_info,
    variable_info = variable_info,
    sample_info_note = sample_info_note,
    variable_info_note = variable_info_note
  )
  
object
```



```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=FALSE}
dim(object)
nrow(object)
ncol(object)
rownames(object) %>% head()
colnames(object)
object[1,1]
```

# **tidyverse verbs**

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=FALSE}
object2 = 
  object %>% 
  activate_mass_dataset(what = "sample_info") %>% 
  mutate(sample_id2 = sample_id)

head(extract_sample_info(object))
head(extract_sample_info(object2))
```


# **apply**

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=FALSE}
##NA number in QC samples for all variables  
object %>% 
  activate_mass_dataset(what = "sample_info") %>% 
  filter(class == "QC") %>% 
  apply(1, function(x){sum(is.na(x))}) %>% 
  head()

##NA number in all samples
object %>% 
  apply(2, function(x){sum(is.na(x))})
```


# **Mutate MS2 data**

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=FALSE}
dir.create("example")
file.copy(
  system.file("ms2_data", package = "massdataset"),
  to = "example",
  overwrite = TRUE, 
  recursive = TRUE
)

object2 = 
mutate_ms2(
  object = object,
  column = "rp",
  polarity = "positive",
  ms1.ms2.match.mz.tol = 10, 
  ms1.ms2.match.rt.tol = 15, 
  path = "example"
)

extract_ms2_data(object2)

```


# **Missing values**

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=FALSE}
library(massdataset)
library(plyr)
data("expression_data")
data("sample_info")
data("variable_info")

object =
  create_mass_dataset(
    expression_data = expression_data,
    sample_info = sample_info,
    variable_info = variable_info,
  )

object

##show missing values plot
show_missing_values(object)

show_missing_values(object[1:10,], cell_color = "white")

###only show subject samples
object %>%
  activate_mass_dataset(what = "sample_info") %>%
  filter(class == "Subject") %>%
  show_missing_values()

###only show QC samples
object %>%
  activate_mass_dataset(what = "expression_data") %>%
  dplyr::select(contains("QC")) %>%
  show_missing_values()

###only show features with mz < 100
object %>%
  activate_mass_dataset(what = "variable_info") %>%
  dplyr::filter(mz < 100) %>%
  show_missing_values(cell_color = "white",
                      show_row_names = TRUE,
                      row_names_side = "left")

##show missing values plot
show_sample_missing_values(object)
show_sample_missing_values(object, color_by = "class")
show_sample_missing_values(object, color_by = "class", order_by = "na")
show_sample_missing_values(object, color_by = "class", order_by = "na",
                           desc = TRUE)

##show missing values plot
show_variable_missing_values(object)
show_variable_missing_values(object, color_by = "mz")

show_variable_missing_values(object, color_by = "rt") +
  scale_color_gradient(low = "skyblue", high = "red") 

show_variable_missing_values(object, color_by = "mz", 
                             order_by = "na")
show_variable_missing_values(object, color_by = "mz", 
                             order_by = "na",
                           desc = TRUE, frequency = TRUE)

```


# **log and scale**

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=FALSE}
library(massdataset)
library(plyr)
data("expression_data")
data("sample_info")
data("variable_info")

object =
  create_mass_dataset(
    expression_data = expression_data,
    sample_info = sample_info,
    variable_info = variable_info,
  )

object

##log
x = log(object, 10)
x
#scale
x2 = scale(x)
x2
```


# **Accessors**

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=FALSE}
library(massdataset)
library(plyr)
data("expression_data")
data("sample_info")
data("variable_info")

object =
  create_mass_dataset(
    expression_data = expression_data,
    sample_info = sample_info,
    variable_info = variable_info,
  )

object

object[1:5,1:3]

object[1:5,]

object[,1:3]

extract_sample_info(object) %>% 
  head()

extract_variable_info(object) %>% 
  head()

extract_expression_data(object) %>% 
  head()


```



# **Explore**

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=FALSE}
data("expression_data")
data("sample_info")
data("variable_info")

object =
  create_mass_dataset(
    expression_data = expression_data,
    sample_info = sample_info,
    variable_info = variable_info,
  )

object %>%
  show_mz_rt_plot()

object %>%
  log(10) %>%
  show_mz_rt_plot()

object %>%
  show_mz_rt_plot(hex = TRUE)
```


