---
title: "Extract data from mass_dataset"
author:
- name: Xiaotao Shen (https://www.shenxt.info/)
date: "Created on 2021-12-04 and updated on `r Sys.Date()`"
output:
  html_document:
    df_print: paged
    toc: no
  pdf_document:
    toc: no
vignette: >
  %\VignetteIndexEntry{Extract data from mass_dataset}
  %\VignettePackage{massdataset}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE, echo=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = TRUE,
  out.width = "100%"
)
```

# **Use `extract_xxx` functions**

We first created a `mass_dataset` class object.

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=TRUE}
library(massdataset)
library(tidyverse)

data("expression_data")
data("sample_info")
data("sample_info_note")
data("variable_info")
data("variable_info_note")

object =
  create_mass_dataset(
    expression_data = expression_data,
    sample_info = sample_info,
    variable_info = variable_info,
    sample_info_note = sample_info_note,
    variable_info_note = variable_info_note
  )
  
object
```

In `massdataset` package, there are a series of functions named as `extract_xxx()`, users can use them to extract data from `mass_dataset` calss object.

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=TRUE}
##sample_info
extract_sample_info(object)
##variable_info
extract_variable_info(object) %>% head()
##expression_data
extract_expression_data(object) %>% head()
##sample_info_note
extract_sample_info_note(object) 
##variable_info_note
extract_variable_info_note(object) 
##ms2_data
extract_ms2_data(object)
##process_info
extract_annotation_table(object)
##process_info
extract_process_info(object)
```

# **Use slot()**

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=TRUE}
slot(object = object, name = "sample_info")
slot(object = object, name = "variable_info") %>% head()
slot(object = object, name = "expression_data") %>% head()
slot(object = object, name = "sample_info_note") 
slot(object = object, name = "variable_info_note") 
slot(object = object, name = "ms2_data") 
slot(object = object, name = "process_info") 
slot(object = object, name = "annotation_table") 
```

# **Use `@`**

`mass_data` class is a S4 object. So we can also use `@`.

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=TRUE}
object@expression_data %>% head()
object@sample_info
object@variable_info %>% head()
object@sample_info_note
object@variable_info_note
object@process_info
object@ms2_data
object@annotation_table
```


# **Session information**

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=TRUE}
sessionInfo()
```
