---
title: "Mutate MS2 into mass_dataset"
author:
- name: Xiaotao Shen (https://www.shenxt.info/)
- affiliation: School of Medicine, Stanford University
  url: http://shenxt.info/
date: "Created on 2021-12-04 and updated on `r Sys.Date()`"
output:
  html_document:
    df_print: paged
    toc: no
  pdf_document:
    toc: no
vignette: >
  %\VignetteIndexEntry{mutate_ms2}
  %\VignettePackage{massdataset}
  % \VignetteEngine{knitr::rmarkdown}
  % \usepackage[utf8]{inputenc}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE, echo=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = TRUE,
  out.width = "100%"
)
```


# **Data preparation**

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=TRUE}
library(massdataset)
library(tidyverse)

data("expression_data")
data("sample_info")
data("sample_info_note")
data("variable_info")
data("variable_info_note")

object =
  create_mass_dataset(
    expression_data = expression_data,
    sample_info = sample_info,
    variable_info = variable_info,
    sample_info_note = sample_info_note,
    variable_info_note = variable_info_note
  )
  
object

###MS2 data (mgf data)
dir.create("demo_data")
file.copy(
  system.file("ms2_data", package = "massdataset"),
  to = "demo_data",
  overwrite = TRUE, 
  recursive = TRUE
)
```


# **Mutate MS2**

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=TRUE}
object2 = 
mutate_ms2(
  object = object,
  column = "rp",
  polarity = "positive",
  ms1.ms2.match.mz.tol = 10, 
  ms1.ms2.match.rt.tol = 15, 
  path = "example"
)

extract_ms2_data(object2)
```
