---
title: "Summary information"
author:
- name: Xiaotao Shen
date: "Created on 2021-12-04 and updated on `r Sys.Date()`"
output:
  html_document:
    df_print: paged
    toc: no
  pdf_document:
    toc: no
vignette: >
  %\VignetteIndexEntry{Summary information}
  %\VignettePackage{massdataset}
  % \VignetteEngine{knitr::rmarkdown}
  % \usepackage[utf8]{inputenc}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE, echo=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = TRUE,
  out.width = "100%"
)
```

For one `mass_dataset` class object, we can get the summary information of it.

# **Data preparation**

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=FALSE}
library(massdataset)
library(tidyverse)

data("expression_data")
data("sample_info")
data("variable_info")

object =
  create_mass_dataset(
    expression_data = expression_data,
    sample_info = sample_info,
    variable_info = variable_info
  )
```

# **Summary information**

Just type this object in the R session.

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=FALSE}
object
```
We can just basic information of the object.

# **Use functions to get the summary information**

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=FALSE}
##dim of object
dim(object)
##row number
nrow(object)
##column number
ncol(object)
##sample number
get_sample_number(object)
#variable number
get_variable_number(object)
```

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=FALSE}
##sample id
colnames(object)
##variable id
rownames(object) %>% 
  head()
##sample id
get_sample_id(object)
##variable id
get_variable_id(object) %>% 
  head()
```

# **Explore**

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=FALSE,
fig.alt=c("Scatter plot of retention time versus m/z for the original dataset.",
          "Scatter plot of retention time versus m/z after log transformation.",
          "Hexbin plot of retention time versus m/z for the original dataset.")}
###show mz rt plot
object %>%
  show_mz_rt_plot()
###should log
object %>%
  `+`(1) %>% 
  log(10) %>%
  show_mz_rt_plot()
###use hex
object %>%
  show_mz_rt_plot(hex = TRUE)
```

# **Missing values**

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=FALSE,
fig.alt=c("Heatmap of missing values across the full dataset.",
          "Heatmap of missing values for the first ten variables with white cells.",
          "Heatmap of missing values for subject samples only.",
          "Heatmap of missing values for QC samples only.",
          "Heatmap of missing values for variables with m/z below 100.",
          "Sample-level missing value summary plot.",
          "Sample-level missing value summary plot colored by sample class.",
          "Sample-level missing value summary plot ordered by missing value count.",
          "Sample-level missing value summary plot ordered by missing value count in descending order.",
          "Variable-level missing value summary plot.",
          "Variable-level missing value summary plot colored by m/z.",
          "Variable-level missing value summary plot colored by retention time.",
          "Variable-level missing value summary plot colored by m/z and ordered by missing value count.",
          "Variable-level missing value percentage plot colored by m/z and ordered by missing value count in descending order.")}
##show missing values plot
show_missing_values(object)

show_missing_values(object[1:10,], cell_color = "white")

###only show subject samples
object %>%
  activate_mass_dataset(what = "sample_info") %>%
  filter(class == "Subject") %>%
  show_missing_values()

###only show QC samples
object %>%
  activate_mass_dataset(what = "expression_data") %>%
  dplyr::select(contains("QC")) %>%
  show_missing_values()

###only show features with mz < 100
object %>%
  activate_mass_dataset(what = "variable_info") %>%
  dplyr::filter(mz < 100) %>%
  show_missing_values(cell_color = "white",
                      show_row_names = TRUE,
                      row_names_side = "left")

##show missing values plot
show_sample_missing_values(object)
show_sample_missing_values(object, color_by = "class")
show_sample_missing_values(object, color_by = "class", order_by = "na")
show_sample_missing_values(object, color_by = "class", order_by = "na",
                           desc = TRUE)

##show missing values plot
show_variable_missing_values(object)
show_variable_missing_values(object, color_by = "mz")

show_variable_missing_values(object, color_by = "rt") +
  scale_color_gradient(low = "skyblue", high = "red") 

show_variable_missing_values(object, color_by = "mz", 
                             order_by = "na")
show_variable_missing_values(object, color_by = "mz", 
                             order_by = "na",
                           desc = TRUE, percentage = TRUE)

```


# **Session information**

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=FALSE}
sessionInfo()
```
