---
title: "Process mass_dataset using tidyverse functions"
author:
- name: Xiaotao Shen (https://www.shenxt.info/)
- affiliation: School of Medicine, Stanford University
  url: http://shenxt.info/
date: "Created on 2021-12-04 and updated on `r Sys.Date()`"
output:
  html_document:
    df_print: paged
    toc: no
  pdf_document:
    toc: no
vignette: >
  %\VignetteIndexEntry{tidyverse_verse}
  %\VignettePackage{massdataset}
  % \VignetteEngine{knitr::rmarkdown}
  % \usepackage[utf8]{inputenc}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE, echo=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = TRUE,
  out.width = "100%"
)
```


# **Introduction**

Before use the functions from tidyverse, we need to tell it which data we want to process (`activate_mass_dataset()`).

# **filter() function**

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=TRUE}
library(massdataset)
library(tidyverse)

data("expression_data")
data("sample_info")
data("sample_info_note")
data("variable_info")
data("variable_info_note")
object =
  create_mass_dataset(
    expression_data = expression_data,
    sample_info = sample_info,
    variable_info = variable_info,
    sample_info_note = sample_info_note,
    variable_info_note = variable_info_note
  )
  
object
```

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=TRUE}
object = 
object %>% 
  activate_mass_dataset(what = "sample_info")
object@activated
```

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=TRUE}
object = 
object %>% 
  activate_mass_dataset(what = "variable_info")
object@activated
```

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=TRUE}
object = 
object %>% 
  activate_mass_dataset(what = "expression_data")
object@activated
```

## Filter samples

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=TRUE}
object2 = 
object %>% 
  activate_mass_dataset(what = "sample_info") %>% 
  dplyr::filter(class == "QC")
object2

```

## Filter variables

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=TRUE}
object2 = 
object %>% 
  activate_mass_dataset(what = "expression_data") %>% 
  dplyr::filter(!is.na(QC_1))
object2

```

