globalVariables(names = c(
  "Exp.intensity",
  "Exp.mz",
  "Lib.intensity",
  "Lib.mz",
  "intensity",
  "mz",
  "sample_id",
  "variable_id",
  "rt",
  "name",
  "variable_id1",
  "variable_id2",
  "ms2_files_id",
  "ms2_spectrum_id",
  "time",
  "x",
  "row ID",
  "row retention time",
  "Injection order",
  "Batch ID",
  "Class",
  "Alignment ID",
  "Average Mz",
  "Average Rt(min)",
  "1",
  "value",
  "study_variable",
  "SMF_ID",
  "SMH",
  "SML_ID",
  "assay",
  "exp_mass_to_charge",
  "retention_time_in_seconds",
  "study_variable",
  "group",
  ".",
  "Level",
  "Total.score",
  "candidate.num"
))